/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package module.test;

import io.vavr.control.Either;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Either either;

        System.out.println(new App().getGreeting());
    }
}
